### ISSUE TITLE
Publish to Google Chrome web store

### ISSUE THREAD

**Issue by dschep** [QOAL/localisetime#1]
Hi. I recently found your extension and really like it. I use both Chrome & Firefox. I've loaded localisetime in chrome and it seems to work with no problems. But of course, I'd rather install it from the store. Could you publish it? Thanks :)

**Comment by QOAL** [comment]
The extension is now available on the Chrome store! :)
https://chrome.google.com/webstore/detail/localise-times/lfapgjogceelfpildippecdikjnljkek?hl=en-GB
