### ISSUE TITLE
Add timezone blacklist option and/or option to require ":" separator

### ISSUE THREAD

**Issue by Toastbroti** [QOAL/localisetime#10]
Some words may be recognized as timezones.

Example: In German the word "mit" (with) following a year.
"In Deutschland war Amazon `2020 mit` einem Umsatz von [...]"
is replaced with
"In Deutschland war Amazon `07:50` einem Umsatz von [...]"

**Comment by QOAL** [comment]
I'll add both of these suggestions.
I was close to adding an ignored abbreviation section when I first added the options.
The settings section just needs a bit of a rework to facilitate adding these.

I've released 1.20.5 for now with a mitigation for this.

**Comment by QOAL** [comment]
1.22.0 is rolling out now, and it includes the ability to ignore timezone abbreviations.
I think that covers everything here.

Thanks for reporting this too, I appreciate it.
