### ISSUE TITLE
Time only localized in TweetDeck if they are the very first entry in a column.

### ISSUE THREAD

**Issue by zuzuvelas** [QOAL/localisetime#13]
Times on TweetDeck only get localized if they are the very first tweet in a given column.

Times seem to be properly localized if viewing a thread of tweets instead of viewing them from the home column or a profiles timeline.

Top of the timeline
![image](https://user-images.githubusercontent.com/1361015/141511984-4aa74f38-19ee-4d8c-ae86-38adb2fa7cf1.png)

Same tweet but now pushed down one (post page refresh)
![image](https://user-images.githubusercontent.com/1361015/141512084-3496bbd8-add7-4687-adfc-d853d7ca963f.png)

**Comment by QOAL** [comment]
Thank you, Zuzu. I'd known about this bug for a good while, and you managed to motivate me into fixing it.
