### ISSUE TITLE
Extension un-pause by itself

### ISSUE THREAD

**Issue by chaoscreater** [QOAL/localisetime#16]
Hi mate,

On certain webpages, the extension seems to un-pause itself? For example, this one will refresh every 2 mins or so and the extension will un-pause and auto convert the times shown on the webpage:

https://status.azure.com/en-us/status

Is it possible to force it to completely be disabled until we manually turn it back on?

**Comment by QOAL** [comment]
Good catch.
The extension was still performing a single pass on page load.

This is fixed by e306d58, and 1.28.4 is in review/rolling out now.
