### ISSUE TITLE
Conversion not working in Ecuador during DST

### ISSUE THREAD

**Issue by Ductomaniac** [QOAL/localisetime#23]
Hi, 
Conversions have been incorrect since daylight saving times started. My system configuration is UTC-05:00. Conversions to EST worked fine before (they were the same time), but now they should be one hour apart but are still in the same time. So before DST, 4:00 PM EST should have converted to 4:00 PM, but after DST 4:00 PM EST should converte to 3:00 PM but it still converts to 4:00 PM

**Comment by Ductomaniac** [comment]
An example here, this is what you typed:
![image](https://user-images.githubusercontent.com/39270391/226708140-5f3b0caa-2150-4bc3-a47b-52630abd3713.png)
And these are the conversions:
![image](https://user-images.githubusercontent.com/39270391/226708196-45354ed1-1535-4773-a3ef-8f7c37c884bf.png)
The former should defintiely be 3:00 PM in my local time.

![image](https://user-images.githubusercontent.com/39270391/226707482-5770a886-28da-4891-aaae-92807b3eca30.png)

Before pushing the convert button:
![image](https://user-images.githubusercontent.com/39270391/226707741-b676c65f-7442-4fc4-82fb-80ea263fd693.png)

After pushing the convert button:
![image](https://user-images.githubusercontent.com/39270391/226707825-2dc82e93-744d-4f07-9865-643b3bae3ca0.png)

**Comment by QOAL** [comment]
Ok, my mind is actually awake this morning.
Could you please check which time zone you have `ECT` set to in the settings?
It may be on the default which is `Eastern Caribbean Time`.
![image](https://user-images.githubusercontent.com/217349/226881700-23128560-745d-4288-94b9-9bfea6da319c.png)

**Comment by QOAL** [comment]
EST has an offset of 300, the same as ECT. So they will show the same times.
Should you be using EDT (or just ET) instead now?

**Comment by Ductomaniac** [comment]
To be honest I don't know what EDT or ET are. I just want the correct times to show, and when it's 4:00 PM in EST it is 3:00 PM in Ecuador. I can make the change manually if you show me how, but the app should definitely just automatically work for us in places that don't do Daylight Savings Time.

**Comment by QOAL** [comment]
Ok, so EST is Eastern Standard Time, this is only observed for half the year. Then it switches to EDT, or Eastern Daylight Time.
ET is a common way to refer to Eastern Time regardless of the time zone it's currently using.

So this switch from EST to EDT is what recently happened, and it's causing you a headache.

I have just added support for handling DST mix ups with American time zones (PT, MT, CT, ET)
By default it'll automatically display the corrected localised time, so your EST should be fixed. (It will visually mark such times with a coloured fringe)
You can disable this behaviour in the settings, and the time will not be corrected on the page, instead the tooltip will mention it.

Please let me know, once you have 1.30.0, if this resolves your issue.
It's available now for Firefox, and will be shortly available for Chrome.

**Comment by Ductomaniac** [comment]
Fantastic! That fixed it, thank you!
