### ISSUE TITLE
GMT+xxxx conversion wrong

### ISSUE THREAD

**Issue by florensie** [QOAL/localisetime#24]
![image](https://user-images.githubusercontent.com/13403842/235114240-45c4e47c-5ab1-4dfd-8259-9cdc8d7f538b.png)
![image](https://user-images.githubusercontent.com/13403842/235114255-bbf75bc0-3a4a-4e22-b5e9-675d5a33e56e.png)

My local time is already GMT+2. LocaliseTime saw GMT and added two hours, while it should see GMT+2 and not convert anything.

**Comment by QOAL** [comment]
Thank you for taking the time to report this, I appreciate it.
It's a silly oversight on my part.
I've managed to fix this over lunch (https://github.com/QOAL/localisetime/commit/c38c738c253670bb759a29930ea4f8ba7ecc8da8), and 1.30.2 has been submitted to AMO and CWS.
